.Dd April 27, 2018
.Dt FREE 1
.Os
.Sh NAME
.Nm free
.Nd display memory information
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a utility that displays the amount of free and used memory in the system.
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh AUTHORS
.Nm
was written by
.An Nan Xiao Aq Mt nan@chinadtrace.org .
