name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: mario-campos/emulate@v1
      with:
        operating-system: openbsd-latest
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/NanXiao/free.git
    - name: make
      run: cd free; make
